opt_in_rules:
  - closure_spacing
  - fatal_error_message
  - force_unwrapping
  - implicitly_unwrapped_optional
  - legacy_multiple
  - legacy_random
  - operator_usage_whitespace

disabled_rules:
  - multiple_closures_with_trailing_closure

indentation: 4
line_length: 100
identifier_name:
  min_length: 4
type_name:
  min_length: 4
function_parameter_count: 6
